version: 2.1

jobs:
  job_1:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - run:
          name: Is this a PR?
          command: echo $CIRCLE_PULL_REQUEST

workflows:
  doot_doot:
    jobs:
      - job_1
