version: 2.1

jobs:
  job_1:
    docker:
      - image: ubuntu:14.04
    steps:
      - run:
          name: Work in Progress
          command: echo abc123

workflows:
  to-be-determined:
     jobs:
       - job_1
