version: 2.1

jobs:
  job_1:
    machine:
      image: ubuntu-1604:201903-01
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Create stuff
          command: |
            mkdir -p my_workspace
            echo "Can we pass this to another workspace?" > my_workspace/echo-output
      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory
          root: my_workspace
          paths:
            - echo-output
  job_2:
    machine:
      image: ubuntu-1604:201903-01
      docker_layer_caching: true
    steps:
      - checkout
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: my_workspace
      - run:
          name: Read from workspace
          command: |
            echo "Hello world!"
            if [[ $(cat my_workspace/echo-output) == "Can we pass this to another workspace?" ]]; then
              echo "Woot! It worked!";
            else
              echo "Nope!"; exit 1
            fi
workflows:
  doot_doot:
    jobs:
      - job_1
      - job_2:
          requires:
            - job_1
